spring:
  application:
    name: hn-reader

# SQLite Database configuration
  datasource:
    url: jdbc:sqlite:hnreader.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

# JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

# Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# template engines
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names: next/*

gg.jte.development-mode: true

# rendering type
view:
  rendering:
    mode: jte
#    mode: thymeleaf