spring.application.name=hn-reader

# SQLite Database configuration
spring.datasource.url=jdbc:sqlite:hnreader.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# template engines
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.excluded-view-names=next/*

gg.jte.development-mode=true

# rendering type
#view.rendering.mode=thymeleaf
view.rendering.mode=jte
